name: Generate Profile Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # 1. Gera o jogo da cobrinha
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: PabliitoxD
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2. Clona o repositório para salvar outros SVGs gerados
      - name: Checkout
        uses: actions/checkout@v3

      # 3. Faz o deploy dos arquivos gerados para a branch 'output'
      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
